// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCoursInfo = "cours_infos"

// CoursInfo mapped from table <cours_infos>
type CoursInfo struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Year      int32     `gorm:"column:year" json:"year"`
	Cours     int32     `gorm:"column:cours" json:"cours"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName CoursInfo's table name
func (*CoursInfo) TableName() string {
	return TableNameCoursInfo
}
