// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSiteMetaDatum = "site_meta_data"

// SiteMetaDatum mapped from table <site_meta_data>
type SiteMetaDatum struct {
	BasesID       int32     `gorm:"column:bases_id" json:"bases_id"`
	PublicURL     string    `gorm:"column:public_url" json:"public_url"`
	Description   string    `gorm:"column:description" json:"description"`
	Keywords      string    `gorm:"column:keywords" json:"keywords"`
	Author        string    `gorm:"column:author" json:"author"`
	OgTitle       string    `gorm:"column:og_title" json:"og_title"`
	OgType        string    `gorm:"column:og_type" json:"og_type"`
	OgDescription string    `gorm:"column:og_description" json:"og_description"`
	OgURL         string    `gorm:"column:og_url" json:"og_url"`
	OgImage       string    `gorm:"column:og_image" json:"og_image"`
	OgSiteName    string    `gorm:"column:og_site_name" json:"og_site_name"`
	GetDate       time.Time `gorm:"column:get_date" json:"get_date"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName SiteMetaDatum's table name
func (*SiteMetaDatum) TableName() string {
	return TableNameSiteMetaDatum
}
