// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTwitterStatusHistory = "twitter_status_histories"

// TwitterStatusHistory mapped from table <twitter_status_histories>
type TwitterStatusHistory struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BasesID   int32     `gorm:"column:bases_id" json:"bases_id"`
	Follower  int32     `gorm:"column:follower" json:"follower"`
	GetDate   time.Time `gorm:"column:get_date" json:"get_date"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TwitterStatusHistory's table name
func (*TwitterStatusHistory) TableName() string {
	return TableNameTwitterStatusHistory
}
